import type { Metadata } from "next";
import "./globals.css";
import { Pathway_Extreme } from "next/font/google";

const pathwayExtreme = Pathway_Extreme({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pathwayExtreme.variable}>
      <body>{children}</body>
    </html>
  );
}
